### ISSUE TITLE
LR - Create - Handle Folder does not exist error

### ISSUE THREAD

**Issue by ludetc** [sh977218/ts-etl-ui#427]

**Comment by sh977218** [comment]
![image](https://github.com/user-attachments/assets/6b353b0b-0cc7-4991-95f8-cd70cc91a17f)

api returns error indicates that source file is not there.

**Comment by sh977218** [comment]
this ticket needs:
1. fix the error message,
2. do not close the modal, so user can fix the data and do another call, without fill the entire form again.
