### ISSUE TITLE
test should be run with no DB reset

### ISSUE THREAD

**Issue by sh977218** [sh977218/ts-etl-ui#461]
in NLM dev server, there will be no reset DB on each run. Our tests should be written in a way that is not depend on data reset.
1. Have a proper tear down on every test. i.e. revert the change to data.
2. Have robust test, that is dynamically check the result. So no tear down needed.

**Comment by ludetc** [comment]
>in NLM dev server, there will be no reset DB on each run
Why not?

>Have a proper tear down on every test. i.e. revert the change to data.
Are you sure you will be able to reset the data? For example, a lot of created data cannot be deleted, so are you talking some sort of flashback?

**Comment by sh977218** [comment]
> > in NLM dev server, there will be no reset DB on each run
> > Why not?
> 
> > Have a proper tear down on every test. i.e. revert the change to data.
> > Are you sure you will be able to reset the data? For example, a lot of created data cannot be deleted, so are you talking some sort of flashback?

how? can UI reset oracle DB?
if we would, you reset the DB, and everyone's data from past will be gone?
